import { Inter } from 'next/font/google'
import '../styles/globals.scss'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from './api/uploadthing/core';
import { Toaster } from 'react-hot-toast';
import AuthProvider from '@/context/AuthProvider';
 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Invoice generator',
  description: 'Generated by collinz Dev',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} class="overflow-hidden">
        <AuthProvider>
      <Toaster
  position="top-center"
  reverseOrder={false}
/>
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <Navbar/>
        {children}
        <Footer/>
 </AuthProvider>
      </body> 
    </html>
  )
}
