import { Inter } from 'next/font/google'
import '../styles/globals.scss'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Invoice generator',
  description: 'Generated by collinz Dev',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}</body>
        <Footer/>
    </html>
  )
}
